name = "TemporalSheaves"
uuid = "18b264b9-e8a0-44aa-a543-ac2aaf56de86"
authors = ["TheCedarPrince <jacobszelko@gmail.com> and contributors"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[weakdeps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Sixel = "45858cf5-a6b0-47a3-bbea-62219f50df47"

[extensions]
TemporalSheavesHypertextExt = ["HypertextLiteral"]
TemporalSheavesTerminalViewExt = ["Sixel", "FileIO"]

[compat]
Catlab = "0.17"
FileIO = "1.18"
HypertextLiteral = "1"
Sixel = "0.1.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
