name = "TemporalSheaves"
uuid = "18b264b9-e8a0-44aa-a543-ac2aaf56de86"
authors = ["TheCedarPrince <jacobszelko@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
